/**
 * analyzer.js — Behavior Analyzer (Stage 4)
 *
 * Reads the summary generated by BehaviorTracker and identifies meaningful patterns.
 * Does NOT directly control the enemy (this happens in Stage 5+).
 */

export class BehaviorAnalyzer {
  /**
   * Analyzes the tracker summary and returns structured metrics and observations.
   * @param {object} summary - The object returned by BehaviorTracker.getSummary()
   * @returns {object} { metrics, observations }
   */
  analyze(summary) {
    const metrics = {
      preferredDirection: 'BALANCED',
      directionConfidence: 0,
      playStyle: 'BALANCED',
      dashUsage: 'LOW',
      stationaryBehavior: 'LOW',
      accuracy: 0,
      predictability: 0,
    };

    const observations = [];

    // --- 1. Attack Preference & Direction ---
    const totalAttacks = summary.totalAttacks || 0;
    if (totalAttacks > 0) {
      const dirs = {
        LEFT: summary.leftAttacks,
        RIGHT: summary.rightAttacks,
        UP: summary.upAttacks,
        DOWN: summary.downAttacks,
      };

      let maxDir = 'BALANCED';
      let maxVal = 0;

      for (const [dir, count] of Object.entries(dirs)) {
        if (count > maxVal) {
          maxVal = count;
          maxDir = dir;
        }
      }

      metrics.directionConfidence = maxVal / totalAttacks;

      if (metrics.directionConfidence >= 0.5) {
        metrics.preferredDirection = maxDir;
        observations.push(`Player strongly prefers ${maxDir} attacks (Confidence: ${(metrics.directionConfidence * 100).toFixed(0)}%).`);
      } else {
        metrics.preferredDirection = 'BALANCED';
        observations.push(`Player attack directions are balanced.`);
      }

      // --- 2. Accuracy ---
      metrics.accuracy = summary.hits / totalAttacks;
      if (metrics.accuracy > 0.7) {
        observations.push('Player has high attack accuracy.');
      } else if (metrics.accuracy < 0.3 && totalAttacks > 5) {
        observations.push('Player attacks frequently miss.');
      }
    } else {
      observations.push('Player has not attacked enough to determine preference.');
    }

    // --- 3. Dash Usage ---
    const durationMins = (summary.roundDuration || 1) / 60;
    const dashesPerMin = summary.dashCount / durationMins;
    
    if (dashesPerMin > 10) {
      metrics.dashUsage = 'HIGH';
      observations.push('Player uses dash frequently.');
    } else if (dashesPerMin >= 2.5) {
      metrics.dashUsage = 'MEDIUM';
    } else {
      metrics.dashUsage = 'LOW';
      if (summary.roundDuration > 10) observations.push('Player rarely dashes.');
    }

    // --- 3.5 Stationary Behavior ---
    const statStreak = summary.stationaryStreak || 0;
    const statRatio = summary.roundDuration > 0 ? (summary.timeStationary / summary.roundDuration) : 0;
    if (statStreak >= 2.5 || statRatio > 0.45) {
      metrics.stationaryBehavior = 'HIGH';
      observations.push('Player remains stationary frequently.');
    } else if (statStreak >= 1.2 || statRatio > 0.25) {
      metrics.stationaryBehavior = 'MEDIUM';
    } else {
      metrics.stationaryBehavior = 'LOW';
    }

    // --- 4. Play Style (Aggressive vs Defensive) ---
    // Aggressive metrics: high close time ratio, high rushes
    // Defensive metrics: high far time ratio, high retreats, low attacks
    const totalPosTime = (summary.timeClose + summary.timeFar) || 1;
    const closeRatio = summary.timeClose / totalPosTime;
    const farRatio = summary.timeFar / totalPosTime;
    
    let aggressionScore = 0;
    
    if (closeRatio > 0.5) aggressionScore += 1;
    if (farRatio > 0.5) aggressionScore -= 1;
    if (summary.rushCount > summary.retreatCount * 1.5) aggressionScore += 1;
    if (summary.retreatCount > summary.rushCount) aggressionScore -= 1;
    if (totalAttacks / durationMins > 30) aggressionScore += 1;
    if (totalAttacks / durationMins <= 10) aggressionScore -= 1;

    if (aggressionScore >= 1) {
      metrics.playStyle = 'AGGRESSIVE';
      observations.push('Player exhibits highly AGGRESSIVE behavior (frequently rushes toward the enemy).');
    } else if (aggressionScore <= -1) {
      metrics.playStyle = 'DEFENSIVE';
      observations.push('Player exhibits highly DEFENSIVE behavior (retreats and stays far away).');
    } else {
      metrics.playStyle = 'BALANCED';
      observations.push('Playstyle is balanced between aggression and defense.');
    }

    // --- 5. Predictability ---
    // Predictability is an arbitrary estimate based on how heavily skewed the behaviors are
    // If they have a preferred direction with >70% confidence, or exclusively rush/retreat, they are predictable.
    
    let predScore = 0;
    if (metrics.playStyle !== 'BALANCED') {
      predScore += 0.3;
      if (metrics.directionConfidence >= 0.75) predScore += 0.4;
      else if (metrics.directionConfidence >= 0.5) predScore += 0.2;
    } else {
      if (metrics.directionConfidence >= 0.25) predScore += 0.2;
    }

    if (summary.rushCount > 10 && summary.rushCount > summary.retreatCount * 5) predScore += 0.4;
    if (summary.dashCount === 0 && summary.roundDuration > 20) predScore += 0.2;

    metrics.predictability = Math.max(0, Math.min(1.0, parseFloat(predScore.toFixed(1))));

    if (metrics.predictability > 0.7) {
      observations.push('Player behavior is highly predictable.');
    } else if (metrics.predictability < 0.3) {
      observations.push('Player behavior is UNPREDICTABLE.');
    }

    return {
      metrics,
      observations
    };
  }
}
